# Generated by Django 3.0.8 on 2020-07-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Student database',
                'db_table': 'Student',
            },
        ),
    ]
